### ISSUE TITLE
[Info] vector<class>, vector<*class> 차이

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#105]
vector<Point*>는 왜 쓰나요..? vector<Point>로도 여러개 저장할 수 있는데.. 음.. 어떤점이 좋나요?

- vector<Point> v1(5);    
  - 5개의 Point 객체를 담는 vector v1 생성, 이 때 default 생성자로 5개 생성됨.
- vector<Point> v2(5, Point(10,10));
  - Point(10,10)을 생성하고 이 익명 객체를 바탕으로 5번의 복사 생성자를 호출하여 vector의 각 칸을 초기화함.
- vector<Point*> v3(5);
  - NULL pointer 5개로 vector의 각 칸을 초기화함.
- vector<Point* v4(5, new Point(20,20);
  - Point(20,20)을 이용해 동적으로 Point객체를 생성하고 그 객체에 대한 주소값을 이용해 Point pointer를 초기화함.

`vector v2(5, Point(10,10));`
> 한 번의 생성자와 5번의 복사생성자가 호출

`vector v4(5, new Point(20, 20));`
> 한 번만 생성자가 호출되고, 주소값 출력결과를 보아 벡터 내의 각 칸의 pointer들은 모두 방금 생성된 같은 객체의 주소를 저장

뭔가 아직도 조금 혼동됩니다..

- https://senticoding.tistory.com/54

**Comment by hochan222** [comment]
> Class 객체는 크기가 아주 작으므로 객체를 벡터에 바로 저장해도 별 상관이 없다. 그러나 일반적인 객체는 대단히 클 수 있으므로 벡터에 직접 객체를 저장하는 것보다는 객체의 포인터를 저장하는 것이 성능상 유리하며 훨씬 더 일반적이다.

```c++
#include <iostream>
#include <vector>
using namespace std;

class Time
{
protected:
     int hour,min,sec;
public:
     Time(int h,int m,int s) { hour=h;min=m;sec=s; }
     void OutTime() { printf("%d:%d:%d ",hour,min,sec); }
};

template<typename C>
void dump(const char *desc, C c)
{
     cout.width(12);cout << left << desc << "==> ";
     for (unsigned i=0;i<c.size();i++) { c[i]->OutTime(); }
     cout << endl;
}

void main()
{
     vector<Time *> vt;
     vt.push_back(new Time(1,1,1));
     vt.push_back(new Time(2,2,2));
     dump("요소 2개",vt);
     vector<Time *>::iterator it;
     for (it=vt.begin();it!=vt.end();it++) {
          delete *it;
     }
}
```

- http://www.soen.kr/lecture/ccpp/cpp4/40-1-4.htm

**Comment by hochan222** [comment]
오오.. 드디어 쓰임새를 찾았습니다..

**Comment by hochan222** [comment]
class vector 안에 class vector 있을경우 값유지가 안돼요..! 

ServerManager Class에서 
```c++
std::vector<Server> m_server;
```

로 했을때는 Server class의 
```c++
std::vector<HttpConfigLocation> m_postLocation;
```
의 값이 유지가 안되는데 

```c++
std::vector<Server*> m_server;
```
포인터로 바꾸면 유지가 됩니다!

이모지 두개되면 이슈 닫겠습니댜!

**Comment by jwon42** [comment]
끝없는 문법 공부.. 고마워요 호찬씨!!
