### ISSUE TITLE
[httpConfig] 유효성 check

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#109]
config 파일에서 아래와 같은 부분은 Server에서 유효성 검사를 해야한다고 생각하고
```
index index.html;
root /Users/holee/Documents/Webserv/;
```
아래와같이 확정적인 경로는 config 에서 유효성 검사를해야한다고 생각합니다. (+ 검사를하면 server 로직을 짜는데 조금 더 깔끔하게 짤 수 있을것 같습니다.)
```
default_error_page ./www/errors/default_error.html;
cgi_path /Users/holee/Documents/Webserv/cgi_tester;
```

 @jwon42  혹시 httpConfig 에서 유효성 검사를 해주실 수 있나요? (파일 존재여부에대한 검사)

**Comment by jwon42** [comment]
네 유틸에 있는 함수를 이용해서 유효성 체크 추가해놓을게요.

```c++
bool isValidFilePath(std::string path)
```
https://github.com/ftinx/webserv/blob/master/includes/Utils.hpp#L68
https://github.com/ftinx/webserv/blob/master/srcs/Utils.cpp#L323
