### ISSUE TITLE
Utils.cpp 필요한 공용 함수들 

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#11]
Utils.cpp 필요한 공용 함수들 

libft c
- [x] isspace
- [x] isdigit
- [x] isprint
- [x] strlen
- [x] strchr
- [x] memset

libft c++
- [x] ltrim
- [x] rtrim
- [x] trim
- [x] split(char set)
- [x] split(string set)

fd set #8
- [x] fdZero
- [x] fdSet
- [x] fdClr
- [x] fdIsSet

tcp #6
- [x] hToNS
- [x] hToNL
- [x] nToHS
- [x] nToHL
- [x] iNetNtoA

time
- [x] getDateTimestamp

etc.
- [x] isFileExists
- [x] isDirExists
- [x] checkBlankLine
- [x] fileToString #55
- [x] stoi

## Spec
- using namespace 안에 정의

**Comment by jwon42** [comment]
getline 은 string 헤더에 있는듯

**Comment by jwon42** [comment]
getMethodType 유틸에 추가 예정
