### ISSUE TITLE
[CGI] auth 처리

### ISSUE THREAD

**Issue by yechoi42** [ftinx/webserv#118]
### 관련 환경변수
AUTH_TYPE
If the server supports user authentication, and the script is protects, this is the protocol-specific authentication method used to validate the user.

REMOTE_USER
If the server supports user authentication, and the script is protected, this is the username they have authenticated as.

REMOTE_IDENT
If the HTTP server supports RFC 931 identification, then this variable will be set to the remote user name retrieved from the server. Usage of this variable should be limited to logging only.

### 관련 헤더
WWW-Authenticate, Authorization 등이 있음. 
```
      auth-scheme    = token
      auth-param     = token "=" ( token | quoted-string )

```

만약 "Basic" 인증 스킴이 사용되었다면, 증명은 다음과 같이 만들어집니다:
사용자명과 비밀번호가 콜론을 이용하여 합쳐집니다(aladdin:opensesame).
그 결과에 대한 문자열을 base64 로 인코딩합니다 (YWxhZGRpbjpvcGVuc2VzYW1l).
 
https://developer.mozilla.org/ko/docs/Web/HTTP/Authentication
https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Authorization

**Comment by hochan222** [comment]
#### HTTP는 액세스 제어와 인증을 위한 프레임워크를 제공합니다. 가장 일반적인 인증 방식은 "Basic" 인증 방식입니다.

RFC 7235는 서버에 의해 클라이언트 요청을 시도(challenge)하고, 클라이언트에 의해 인증 정보를 제공하기 위해 사용될 수 있는 HTTP 인증 프레임워크를 정의합니다.

- 가장 일반적인 인증 스킴은 아래에서 좀 더 자세하게 소개할 "Basic" 인증 스킴입니다. IANA는 인증 스킴의 목록을 유지하고 있으나, Amazon AWS와 같은 호스트 서비스에 의해 제공되는 다른 스킴도 존재합니다.

- __Basic (RFC 7617를 보십시오. base64-encoded credentials. 더 많은 정보는 아래를 확인하십시오.),__
- __Bearer (RFC 6750를 보십시오. bearer tokens to access OAuth 2.0-protected resources),__
- __Digest (RFC 7616를 보십시오. Firefox에서는 md5 해싱만 지원합니다. SHA 암호화 지원을 위하여 bug 472823을 확인하십시오.),__
- __HOBA (RFC 7486 (draft)를 보십시오. HTTP Origin-Bound Authentication, digital-signature-based),__
- __Mutual (draft-ietf-httpauth-mutual를 참조하십시오),__
- __AWS4-HMAC-SHA256 (AWS docs를 참조하십시오).__

```
Authorization: <type> <credentials>
Proxy-Authorization: <type> <credentials>
WWW-Authenticate: <type> realm=<realm>[, charset="UTF-8"]
```
- type
<img src="https://user-images.githubusercontent.com/22424891/112269692-0c1e8880-8cbc-11eb-82bf-f3f411765663.png" height="300px"/>

- example
```
WWW-Authenticate: Basic realm="Access to the staging site", charset="UTF-8"
```

<img src="https://user-images.githubusercontent.com/22424891/112271745-a67fcb80-8cbe-11eb-822b-2b79a8f9706b.png" height="300px" />

- (프록시) 서버가 주어진 리소스에 대한 접근 권한을 얻기 위해 적절하지 않은 유효한 인증 정보를 수신한다면, 서버는 403 Forbidden 상태 코드로 응답하여야 합니다.  401 Unauthorized나 407 (en-US) Proxy Authentication Required와는 다르게, 해당 사용자에 대한 인증은 불가능합니다.
-  프록시의 경우, 요청에 대한 상태 코드는 407 (en-US) (Proxy Authentication Required)이다.

```# 참고 ```
- https://developer.mozilla.org/ko/docs/Web/HTTP/Authentication
- https://tools.ietf.org/html/rfc7235

**Comment by hochan222** [comment]
1. 브라우저가 GET 요청을 를 서버로 보낸다.
2. 서버가 `HTTP/1.1 401 Unauthorized`, `WWW-Authenticate: Basic realm="Access to the staging site", charset="UTF-8"`를 브라우저에게 보낸다. ( "Basic" 인증의 경우, 교환은 안전을 위해 HTTPS (TLS) 연결 위에서 발생하여야 한다. )
3. 브라우저가 `Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l` 를 서버로 보낸다
4. 서버는 `HTTP/1.1 200 OK`, `HTTP/1.1 403 Forbidden` 을 브라우저로 보낸다.
---

## User-Agent (Basic)

1. 사용자로부터 사용자 name와 password를 가져옵니다.
  - name is "test", password is the string "123"
2. 단일 콜론 (":")으로 name와 password를 구성합니다. followed by the Unicode character U+00A3 (POUND SIGN).
  - 't' 'e' 's' 't' ':' '1' '2' '3' pound 
3. 사용자 password를 옥텟 시퀀스로 인코딩합니다 
 - 74  65  73  74  3A  31  32  33  C2  A3
4. 옥텟 시퀀스를 Base64로 인코딩하여 ASCII 문자열로 변환합니다.
  -  dGVzdDoxMjPCow==
5. basic-credentials을 얻습니다.
  - Authorization: Basic dGVzdDoxMjPCow==
  - Proxy-Authorization: Basic dGVzdDoxMjPCow==

---
## Server
1. 서버가 액세스 보호 개체에 대한 요청을 수신하고 허용 가능한 Authorization 헤더 필드가 전송되지 않은 경우 "401 Unauthorized"상태 코드 및 WWW-Authenticate 헤더 필드와 Digest 스키마로 응답한다.

**Comment by hochan222** [comment]
`# Basic`

- Base64를 사용하여 인코딩 된 암호 쌍으로된 사용자 ID /로 자격 증명을 전송하는 인증 체계입니다.
-  이 체계는 사용자의 안전한 방법으로 간주되지 않습니다.
-  scheme와 parameter 이름은 모두 대소 문자를 구분하지 않습니다.

<img src="https://user-images.githubusercontent.com/22424891/112276627-4db33180-8cc4-11eb-8285-cd5cce66bea7.png" height="100px"/>

-  token68 구문은 66 개의 예약되지 않은 URI 문자를 허용합니다.
- 유일하게 허용되는 값은 "UTF-8"이다.
-  참고 : [RFC2831]의 섹션 2.1.1과의 일관성을 위해 'charset'이라는 이름이 선택되었습니다 . 더 나은 이름은 'accept-charset'이 될 것입니다. 메시지가 나타나는 것이 아니기 때문입니다.

- Reusing Credentials
  - 재사용 가능
    - http://example.com/docs/
    - http://example.com/docs/test.doc
    - http://example.com/docs/?page=1
  - 재사용 불가능 (인증 범위 외부에 있는것으로 간주)
    - http://example.com/other/
    - https://example.com/docs/

---

```
WWW-Authenticate: Newauth realm="apps", type=1,
                       title="Login to \"apps\"", Basic realm="simple"
```


<br>

`# 참고`
- [rfc7616: HTTP Digest Access Authentication](https://tools.ietf.org/html/rfc7616)
- [rfc7617: The 'Basic' HTTP Authentication Scheme](https://tools.ietf.org/html/rfc7617)
- [rfc 7235:   Hypertext Transfer Protocol (HTTP/1.1): Authentication](https://tools.ietf.org/html/rfc7235#section-2.1)

**Comment by hochan222** [comment]
## server (digest)

> The Hypertext Transfer Protocol (HTTP) provides a simple challenge-
   response authentication mechanism that may be used by a server to
   challenge a client request and by a client to provide authentication
   information.
   
- __Client__: challenge
- __Server__: authentication

#### 이 사양은 다음 알고리즘을 정의합니다. 
- SHA2-256 (구현 필수) 
- SHA2-512 / 256 (백업 알고리즘) 
- MD5 (역 호환성). 

```
 HTTP/1.1 401 Unauthorized
 WWW-Authenticate: Digest
       realm="api@example.org",
       qop="auth",
       algorithm=SHA-512-256,
       nonce="5TsQWLVdgBdmrQ0XsxbDODV+57QdFR34I9HAbC/RVvkK",
       opaque="HRPCssKJSGjCrkzDg8OhwpzCiGPChXYjwrI2QmXDnsOS",
       charset=UTF-8,
       userhash=true
```

**Comment by hochan222** [comment]
<img src="https://user-images.githubusercontent.com/22424891/112434245-b1059800-8d86-11eb-9f66-2b0e52549881.png" height="300px" />

- [Why does the RFC 7617 auth basic standard put pound before converting to base64?](https://stackoverflow.com/questions/66794994/why-does-the-rfc-7617-auth-basic-standard-put-pound-before-converting-to-base64)

**Comment by hochan222** [comment]
[Why does the RFC 7617 auth basic standard put pound before converting to base64?](https://stackoverflow.com/questions/66794994/why-does-the-rfc-7617-auth-basic-standard-put-pound-before-converting-to-base64)

**Comment by hochan222** [comment]
오...! 대박.. 드디어 깨우쳤습니댜..

1. 인증 필요한 path로 요청이오면 헤더를 추가해서 보낸다. (서버가)

```
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="simple"
content-language: ko, en
content-length: 0
content-type: text/html; charset=UTF-8
date: Thu, 25 Mar 2021 17:07:29 KST
server: ftnix/1.0 (MacOS)
status: 401
```

2. `WWW-Authenticate: Basic realm="simple"` 이 헤더를 붙이면 브라우저가 자동으로 아래와같이 띄워줍니다.

<img src="https://user-images.githubusercontent.com/22424891/112439485-80c0f800-8d8c-11eb-9bf8-1ebd8d9019bf.png" height="300px" />

3. username과 password를 입력하면 서버에 자동으로 get요청을 보냅니다.

```
GET / HTTP/1.1
Host: localhost:8080
Connection: keep-alive
Cache-Control: max-age=0
Authorization: Basic aG9sZWU6aG9sZWU=
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Sec-Fetch-Dest: document
Accept-Encoding: gzip, deflate, br
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
```

4. `Authorization: Basic aG9sZWU6aG9sZWU=` 이렇게 붙어서 요청이오면 저희가 로직짜서 보내주거나 401 404 띄우면 될것 같습니다.

**Comment by hochan222** [comment]
저희 같은 경우 한다면 getMethod 최상단에서 root path로 요청하는게 맞겠져..?

**Comment by hochan222** [comment]
@jwon42  .htpassword 폴더 안에 아이디 패스워드 인코딩된거 개행으로 나뉜거 해독 비교
