### ISSUE TITLE
[Request] body parse bug

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#132]
@yechoi42  실험도중 버그인것 같아서 이슈달았습니다. sendresponse() 아래 부분 주석 풀고 

```c++
	/* config Method */
	response = get("/hi", this->m_requests[clientfd], response, Server::getDirectory);
```

브라우저에서 http://localhost:8080/hi 로 접속시 GET요청이라서 body에 아무것도 없어야하는데 아래와같이 body에 이상한게 껴있습니다. 확인 한번만 해주세요!

![image](https://user-images.githubusercontent.com/22424891/111748232-9be6c000-88d3-11eb-9f46-83f90a865838.png)

**Comment by yechoi42** [comment]
아맞아요.. 저번에 뭐 수정하다가 다시 버그가 생긴 걸 확인했는데 고쳐놓을게요
