### ISSUE TITLE
[Server] vector iterator push_back() 코딩 질문..?

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#134]
Server::noteHttpConfigLocation() 에서 vector에 넣을때 다음 두가지 형식이있는데 2번이 위험하나요?

*location_iter는 이터레이터 입니댜!

1. 
```c++
this->m_getLocation.push_back(HttpConfigLocation(*location_iter));
```

2.
```c++
this->m_getLocation.push_back(*location_iter);
```

- https://stackoverflow.com/questions/66711186/is-it-safe-to-not-use-the-constructor-when-push-back-the-iterator-of-vectorclas

**Comment by yechoi42** [comment]
푸시백 할 때 값이 복사돼서 상관없을 것 같아요. 오히려 두번째 방법이 낫지 않을까요? 첫번째는 생성 + 복사, 두번째는 복사만이라서요. 

>Yes, std::vector<T>::push_back() creates a copy of the argument and stores it in the vector.
> 출처: https://stackoverflow.com/questions/2275076/is-stdvector-copying-the-objects-with-a-push-back

> The content of val is copied (or moved) to the new element.
> 출처: http://www.cplusplus.com/reference/vector/vector/push_back/

**Comment by hochan222** [comment]
오오..! stackoverflow에서도 똑같이 말해주셨습니다.. 감사합니다 ㅠㅠ 

생각해보면 당연한건데 iterator라서 불안했던것같아요.. (뭔가 처음 써보다보니...?)

@jwon42 님이 보시면 닫아주세용!

**Comment by jwon42** [comment]
이터레이터 어려워요 @.@ 확인했습니다
