### ISSUE TITLE
[Config] 본인의 .conf 만들기

### ISSUE THREAD

**Issue by yechoi42** [ftinx/webserv#136]
각자 로컬에서 root가 달라지니
본인의 .conf 파일을 만들어두면 테스트하기 좋을 것 같아 제안합니다.

**Comment by jwon42** [comment]
필요합니다. config 폴더 생성 후 각자 닉네임.conf 파일로 만들어 놓고 테스트하면 될 것 같습니다.

**Comment by hochan222** [comment]
확인했습니다!
