### ISSUE TITLE
[Response] setPublicFileDocument 문제

### ISSUE THREAD

**Issue by jwon42** [ftinx/webserv#137]
response의 setPublicFileDocument에서 publicFileToString 함수를 사용합니다.
file path에 "./www/"를 붙여 반환해주는 함수를 사용해서 ./www/ 를 붙이는 번거로움을 줄이는 역할일텐데

getMethod 에서 파일을 요청받고 응답 할 때 
location block의 root element 존재 여부에 따라 저 함수를 사용할 수 없는 상황이 발생합니다.
setPublicFileDocument 또는 publicFileToString를 수정하는게 좋을지 getMethod에 맞는 함수를 추가하는게 좋을지 의견 구합니다.

**Comment by hochan222** [comment]
안그래도 configfile location 어제 만들면서 같은 생각을했습니다. 제가 root path도 지원하도록 response에서 메소드 만들겠습니다.
