### ISSUE TITLE
x

### ISSUE THREAD

**Issue by jwon42** [ftinx/webserv#147]

**Comment by jwon42** [comment]
@hochan222 삭제해주세요~! 실수로..ㅋㅋㅋ

**Comment by hochan222** [comment]
헤헿 이슈는 삭제가 안되더라구용

**Comment by jwon42** [comment]
엇 그래요? 레포 만든 사람은 우측 아래 delete 버튼 있다던데 아닌가보네요. ㅠㅠㅎㅎ

**Comment by hochan222** [comment]
제가 못찾는거일수도있지만 이 페이지 안에는 없나봐요! ㅋㅋㅋㅋㅋ 아무리 찾아도 없네용 힣 ㅠㅠ
