### ISSUE TITLE
[Request, Response] 한 소켓에서 여러 요청이 발생했을 때에 대한 처리

### ISSUE THREAD

**Issue by jwon42** [ftinx/webserv#148]
get method 테스트 중 문제를 발견했습니다.
로직에 문제가 없다고 생각하는데 이상하게 content-type 이 갱신되지 않아서
로그를 찍어보니 여러번 요청이 발생했을 때 첫번째 요청 이후 파싱된 값이 갱신되지 않습니다.

첫번째 요청을 `http://127.0.0.1:8080/style.css` 로 보내면 request 에서 정상적으로  path를 /style.css 로 저장하지만
두번째 요청을 `http://127.0.0.1:8080/script.js` 로 보내면 request 의 path가 여전히 /style.css 입니다.

요청이 들어온 순서대로 request 와 response를 queue로 연동하여 순서대로 반환하는게 필요하지 않을까요?
제가 잘못 이해했거나 다른 해결 방법이 있으면 의견 얘기해주세요!

**Comment by jwon42** [comment]
get method 테스트 중 문제를 발견했습니다.
로직에 문제가 없다고 생각하는데 이상하게 content-type 이 갱신되지 않아서
로그를 찍어보니 여러번 요청이 발생했을 때 첫번째 요청 이후 파싱된 값이 갱신되지 않습니다.

첫번째 요청을 `http://127.0.0.1:8080/style.css` 로 보내면 request 에서 정상적으로  path를 /style.css 로 저장하지만
두번째 요청을 `http://127.0.0.1:8080/script.js` 로 보내면 request 의 path가 여전히 /style.css 입니다.

요청이 들어온 순서대로 request 와 response를 queue로 연동하여 순서대로 반환하는게 필요하지 않을까요?
제가 잘못 이해했거나 다른 해결 방법이 있으면 의견 얘기해주세요!

**Comment by hochan222** [comment]
아.. 저희가 인스턴스를 초기화나 삭제를 안해서 그런걸수도 있을것같습니다. Close된다음에 초기화, 삭제 과정이 현재 없긴합니댜.. 음음..

**Comment by hochan222** [comment]
근데 보통은 덮어써져야 지금 짠로직에 맞는데 그문제는 아닌것같기도 합니댜.. 음음

**Comment by hochan222** [comment]
아.. 말씀하신것처럼 들어오는 순서문제일수도 있을것같네요..!
