### ISSUE TITLE
[Base64] encoder, decoder 구현

### ISSUE THREAD

**Issue by jwon42** [ftinx/webserv#158]
이미지를 요청받은 경우 응답할 때 필요합니다.
제가 공부해서 구현해볼게요.

https://developer.mozilla.org/en-US/docs/Glossary/Base64
https://rangsub.tistory.com/8

**Comment by hochan222** [comment]
혹시 Base64가 평가 기준에 있었나요? 어제 집가서 찾아봤는데 http표준에는 없어서 여쭤봤습니댜. 뭔가 다른 팀에 있는거보니 해야하는건 맞는것같습니댜

https://stackoverflow.com/questions/13265902/http-content-encoding-base64

**Comment by jwon42** [comment]
그럼 일단 보류~!

**Comment by hochan222** [comment]
#118  용도 찾았습니다. 

auth 와 관련있습니다.

- Basic (RFC 7617를 보십시오. base64-encoded credentials. 더 많은 정보는 아래를 확인하십시오.),

**Comment by hochan222** [comment]
@jwon42  
전체적인 로직은 다음과 같습니다. 맨 아래 참조해 주세요! #118

**Comment by hochan222** [comment]
#186

**Comment by jwon42** [comment]
https://github.com/Caceresenzo/42/blob/1f3f370bfa/webserv/source/base64/Base64.cpp

위 코드가 간결해서 잘 짰다 하고 보고 있었는데

원본은 여기였다는거.. ㅋㅋ
http://www.cplusplus.com/forum/beginner/51572/

**Comment by hochan222** [comment]
오오 ㅋㅋㅋㅋㅋㅋㅋ 진짜 깔끔합니댜.. ㅋㅋㅋㅋㅋㅋㅋㅋ 근본의 cplusplus

**Comment by jwon42** [comment]
https://github.com/adamvr/arduino-base64
