### ISSUE TITLE
[Request] path 기준 문제

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#167]
- 현재 상태
```
URL: localhost:8080 => path = "/"
URL: localhost:8080/ => path = "/"
URL: localhost:8080/directory => path = "/directory"
URL: localhost:8080/directory/ => path = "/directory/"
```

- 원하는 상태
```
URL: localhost:8080 => path = "/"
URL: localhost:8080/ => path = "/"
URL: localhost:8080/directory => path = "/directory/"
URL: localhost:8080/directory/ => path = "/directory/"
```

일관되게 request에서 항상 / 로 끝나는 경우처럼 일관돼야한다고 생각합니다. 어떻게 생각하시나요?

**Comment by hochan222** [comment]
@yechoi42 @jwon42

**Comment by hochan222** [comment]
https://tools.ietf.org/html/rfc3986#section-3.3

      path          = path-abempty    ; begins with "/" or is empty
                    / path-absolute   ; begins with "/" but not "//"
                    / path-noscheme   ; begins with a non-colon segment
                    / path-rootless   ; begins with a segment
                    / path-empty      ; zero characters

      path-abempty  = *( "/" segment )
      path-absolute = "/" [ segment-nz *( "/" segment ) ]
      path-noscheme = segment-nz-nc *( "/" segment )
      path-rootless = segment-nz *( "/" segment )
      path-empty    = 0<pchar>
     segment       = *pchar
      segment-nz    = 1*pchar
      segment-nz-nc = 1*( unreserved / pct-encoded / sub-delims / "@" )
                    ; non-zero-length segment without any colon ":"

      pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

path 맨끝에 항상 '/' 가 오는건 표준으로 나와있습니다.!

**Comment by yechoi42** [comment]
좋아요 수정할게요!

**Comment by hochan222** [comment]
@jwon42

**Comment by jwon42** [comment]
생각해보니 request보다는 그 이후에 필요한 곳(get method 파트 등)에서 작업하는게 좋을 것 같기도 합니다.
 
`/`를 붙여주기 위해서 파일인지 폴더인지 유효성 체크를 해야하는데
그럼 location block을 모두 순회하며 root와 결합해야하고 해당 작업은 그 이후인 method 처리에서도 중복적으로 일어납니다.

**Comment by hochan222** [comment]
맞네요.. 제가 생각이 짧았네요 저도 같은 생각입니다.

**Comment by jwon42** [comment]
같이 생각하는거죠~~~ @yechoi42 확인하면 close~!
