### ISSUE TITLE
ServerManager.hpp 설계

### ISSUE THREAD

**Issue by yechoi42** [ftinx/webserv#17]

**Comment by hochan222** [comment]
## Class Diagram

<img src="https://user-images.githubusercontent.com/22424891/108956542-3aa44600-76b3-11eb-823c-dffdaa3d01d2.png" height="300px" />

## Flow Chart

<img src="https://user-images.githubusercontent.com/22424891/108956862-c7e79a80-76b3-11eb-952c-ae3e1c520b85.png" height="700px" />

## File dir

<img src="https://user-images.githubusercontent.com/22424891/108957028-11d08080-76b4-11eb-9a09-837736d88737.png" height="700px" />
