### ISSUE TITLE
[Request] config를 반영한 재설정

### ISSUE THREAD

**Issue by yechoi42** [ftinx/webserv#171]
path가 /directory/aaa.txt라고 했을때
directory 로케이션 블록의 root 를 User/yechoi/ftinx라고 하면
path를 User/yechoi/ftinx/aaa.txt로 재설정하는 과정입니다. 

config를 반영해야하기 때문에 위치는 Server가 될듯합니다.
그리고 server상의 허용 메소드 상의 location블록(ex std::vector<HttpConfigLocation> m_headLocation)을 비교하기 때문에
그 과정에서 405 처리가 가능할 것 같습니다.

**Comment by jwon42** [comment]
퐈이팅
