### ISSUE TITLE
[Request] Chunck 로직 생각하기

### ISSUE THREAD

**Issue by yechoi42** [ftinx/webserv#19]
- [x] Flow Chart
- [x] 메세지 그만 받아야 할 조건 확인
- [x] 구현
- [x] chunked 외의 value(compress, deflate, gzip, identity) 처리 방법 알아보기

**Comment by yechoi42** [comment]
request 메세지 수신을 멈추는 조건은 다음과 같습니다.

1. 클라이언트가 Transfer-Encoding: Chunked 로 메세지를 보냈다면, chunk의 길이가 0일 때 메세지 수신을 완료
![image](https://user-images.githubusercontent.com/61399588/110205615-53cfa280-7ebc-11eb-9411-ac6319a28224.png)

2. 클라이언트가 Content-Length 헤더를 보냈다면 해당 길이만큼 바디를 읽었을 때 완료
3. 메세지 바디가 없는 경우('\r\n'이 연달아 두번 이어질 때)

https://stackoverflow.com/questions/4824451/detect-end-of-http-request-body

**Comment by hochan222** [comment]
Transfer-Encoding이나 content-length 둘중 하나는 반드시 들어오는걸로 처리하면 되나요?

**Comment by hochan222** [comment]
> Transfer-Encoding이나 content-length 둘중 하나는 반드시 들어오는걸로 처리하면 되나요?

답변 : 그렇습니다.

**Comment by hochan222** [comment]
chunked 외의 value(compress, deflate, gzip, identity) 처리 방법 알아보기

=> @yechoi42  chunked만 구현하면 됩니다.!
