### ISSUE TITLE
Request Config hpp 요소 정하기

### ISSUE THREAD

**Issue by jwon42** [ftinx/webserv#2]
Parsing Config hpp 요소 정하기

### request
- version
- method
- path

### header
- Accept-Charsets
- Content-Location
- Referer
- Accept-Language
- Content-Type
- Retry-After
- Allow
- Date
- Server
- Authorization
- Host
- Transfer-Encoding
- Content-Language
- Last-Modified
- User-Agent
- Content-Length
- Location
- WWW-Authenticate

### body
- body

### cgi
- version

## subject

- It must be conditionnal compliant with the rfc 7230 to 7235 (http 1.1) but you need to implement only the following headers
-  We will consider that nginx is HTTP 1.1 compliant and may be use to compare headers and answer behaviors

**Comment by jwon42** [comment]
작성중, 협의 필요.

|      | 이름                     | 자료형 | 종류      | 접근자  | 역할                           | vs nginx                                                     |
| :--: | ------------------------ | ------ | --------- | ------- | ------------------------------ | ------------------------------------------------------------ |
|  1   | m_uri                    | string | data      | private | getter                         | location 블록 `{` 시작 전                                    |
|  2   | m_root_path              | string | data      | private | 웹서버 소프트웨어 이름         | [root](http://nginx.org/en/docs/http/ngx_http_core_module.html#root) |
|  3   | m_methods                | vector | data      | private | 허용 메소드                    | [limit_except](http://nginx.org/en/docs/http/ngx_http_core_module.html#limit_except) |
|  4   | m_autoindex              | bool   | data      | private | 오토인덱스 설정                | [autoindex](http://nginx.org/en/docs/http/ngx_http_autoindex_module.html#autoindex/) |
|  5   | m_auth_basic             | string | data      | private | 인증 영역 이름                 | [auth_basic](http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html) |
|  6   | m_auth_basic_file        | string | data      | private | 인증 파일 데이터               | [auth_basic_file](http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html) |
|  7   | m_index                  | string | data      | private | 인덱스 파일                    | [index](http://nginx.org/en/docs/http/ngx_http_index_module.html#index) |
|  8   | m_cgi_extensions         | vector | data      | private | 허용하는 cgi 확장자            |                                                              |
|  9   | m_cgi_path               | string | data      | private | cgi 경로                       |                                                              |
|  10  | m_max_body_size          | size_t | data      | private | Content-Length 헤더 의 최대 값 | [client_max_body_size](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) |
|  11  | m_default_error_page     | string | data      | private | 기본 에러 페이지 경로          | [error_page](http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page) |
|  12  | get_m_uri                |        | method    | public  | getter                         |                                                              |
|  13  | get_m_root_path          |        | method    | public  | getter                         |                                                              |
|  14  | get_m_methods            |        | method    | public  | getter                         |                                                              |
|  15  | get_m_autoindex          |        | method    | public  | getter                         |                                                              |
|  16  | get_m_auth_basic         |        | method    | public  | getter                         |                                                              |
|  17  | get_m_auth_basic_file    |        | method    | public  | getter                         |                                                              |
|  18  | get_m_index              |        | method    | public  | getter                         |                                                              |
|  19  | get_m_cgi_extensions     |        | method    | public  | getter                         |                                                              |
|  20  | get_m_cgi_path           |        | method    | public  | getter                         |                                                              |
|  21  | get_m_max_body_size      |        | method    | public  | getter                         |                                                              |
|  22  | get_m_default_error_page |        | method    | public  | getter                         |                                                              |
|  17  | Location                 |        | generator | public  | 생성자                         |                                                              |

**Comment by hochan222** [comment]
## Flow Chart

<img src="https://user-images.githubusercontent.com/22424891/108952201-738cec80-76ac-11eb-8500-a7246ccf8a5b.png" height="500px" />

## Class Diagram

<img src="https://user-images.githubusercontent.com/22424891/108953107-f95d6780-76ad-11eb-9d7f-864023b4115e.png" height="500px" />
