### ISSUE TITLE
[Request] m_reset_path 문제

### ISSUE THREAD

**Issue by jwon42** [ftinx/webserv#242]
config file에서 test location 블록을 만들고 index도 설정 후 
get 요청을 날린 경우 파일이 존재함에도 불구하고 404에러가 뜨는 문제

- http://localhost:8080/test 에 get요청
- methodGET에서 m_reset_path을 프린트해보니 test path가 붙지 않은 상태의 root 패스만 출력됨

**Comment by yechoi42** [comment]
fake news out!!!!
