### ISSUE TITLE
[CGI] 리팩토링

### ISSUE THREAD

**Issue by yechoi42** [ftinx/webserv#267]
CGI 성능 개선을 위한 리팩토링

### 기존의 플로우
1. client로부터 getMessage(readProcess)
2. cgi에 건내주기(writeProcess)
3. cgi에서 읽어오기(readProcess)
4. client에 응답 건내주기(writeProcess)

### 바꿀 플로우
1. client로부터 getMessage(readProcess)
2. cgi에 건내주기(writeProcess) --> 여기까지 동일
3. cgi에서 읽어주고 상태코드/헤더가 왔는지 확인하기(readProcess)
3-1. if true, 상태코드와 헤더 세팅하고 writefd 켜주기
3-2. if false, 3번으로 또 들어올 수 있게 처리
4. 상태코드와 헤더가 세팅됐는지 확인하기(writeProcess)
4-1. if true, client로 상태코드와 헤더 보내기
     -> 이미 보냈다는 플래그 설정
     -> dup2(parent_read, sockfd)로 client 소켓 파이프에 직접 물리기
4-2. if false, 4번으로 다시 돌아오게 처리

**Comment by yechoi42** [comment]
### 바꿀 플로우 v2 
1. executeCgi에서 parent_read가 아니라 socket 바로 연결하기
2. client로부터 getMessage(readProcess)
3. cgi에 건내주기(writeProcess)
4. readProcess에서 socket에서 recv MSG_PEEK 옵션으로 훔쳐읽어서 header만 보내기
4-1. recv 의 커서 위치를 헤더 뒤로 보내서 나머지는 cgi에서 직접 보냄

두방법의 리팩토링 모두 실패. 시도 기록은 첫번째껀 feature/cgi, 두번째는 feature/newcgi 브랜치에. 다른 최적화부터 먼저하기로.

**Comment by hochan222** [comment]
### 기록

- 두 방법의 시도에서 dup2 까지는 이상없이잘 진행됨.
- 단지 dup2(parent_read, client_fd) 를 할때 client_fd로 보내지는지는 확인못함. 
- dup2(parent_read, fd) 에서 fd를 read하면 잘 읽어진다.
