### ISSUE TITLE
[Response] OPTIONS

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#28]
OPTIONS

- [x] Flow Chart
- [x] 구현

**Comment by yechoi42** [comment]
curl을 이용하여 OPTIONS 요청을 서버에 보냄으로써 서버에서 지원하는 method를 확인할 수 있다.

`curl -X OPTIONS http://example.org -i`
요청을 보내면, 응답에 Allow헤더가 포함되어서 오는데, 이를 통해 허용되는 메소드를 확인할 수 있다.

```
HTTP/1.1 200 OK
Allow: OPTIONS, GET, HEAD, POST
Cache-Control: max-age=604800
Date: Thu, 13 Oct 2016 11:45:00 GMT
Expires: Thu, 20 Oct 2016 11:45:00 GMT
Server: EOS (lax004/2813)
x-ec-custom-error: 1
Content-Length: 0
```

https://developer.mozilla.org/ko/docs/Web/HTTP/Methods/OPTIONS

**Comment by hochan222** [comment]
혹시 path가 달라지면 allow 메세지도 달라지나요? 전체 지원인가요 개별 url 지원인가요?

**Comment by yechoi42** [comment]
@hochan222 옷 이부분을 어느정도 구현해놓으셨네요?! 지금 확인했어요. path에 따른 허용 메소드는 저희가 정하면 될 것 같아요. *이나 특정 path나 다 같은 게 구현하기는 쉽겠죠. 지금 코드상에는 허용 메소드가 네개로 돼있는데, 다른 것들을 추가할지도 얘기해봐야 할 것 같아요. 제 생각엔 모든 메소드가 다 들어가야 하지 않나 싶습니다.

**Comment by hochan222** [comment]
@yechoi42 네넵! 좋아요!
