### ISSUE TITLE
[CGI] php-cgi 추가

### ISSUE THREAD

**Issue by yechoi42** [ftinx/webserv#282]

**Comment by hochan222** [comment]
>  PHP CGI는 비표준 SCRIPT_FILENAME에 의존합니다 .
- https://woozle.org/papers/php-cgi.html
- https://bugs.php.net/bug.php?id=28227

**Comment by hochan222** [comment]
- Your program should set the following Meta-Variables
  - [x] AUTH_TYPE
  - [x] CONTENT_LENGTH
  - [x] CONTENT_TYPE
  - [x] GATEWAY_INTERFACE
  - [x] PATH_INFO
  - [x] PATH_TRANSLATED
  - [x] QUERY_STRING
  - [x] REMOTE_ADDR
  - [x] REMOTE_IDENT
  - [x] REMOTE_USER
  - [x] REQUEST_METHOD
  - [x] REQUEST_URI
  - [x] SCRIPT_NAME
  - [x] SERVER_NAME
  - [x] SERVER_PORT
  - [x] SERVER_PROTOCOL
  - [x] SERVER_SOFTWARE

- https://www.whoishostingthis.com/compare/cgi-access/variables/

**Comment by hochan222** [comment]
![image](https://user-images.githubusercontent.com/22424891/114368152-17c4e700-9bb8-11eb-8b89-0bdb386758cc.png)


php-mac/lib/php/build/run-tests.php

**Comment by hochan222** [comment]
https://aprelium.com/data/doc/2/abyssws-linux-doc-html/cgivars.html

**Comment by hochan222** [comment]
```

	/*
	** cgi
	*/
	map["AUTH_TYPE"] = ""; //auth 인증 type ex=> cookie
	map["CONTENT_LENGTH"] = "";
	map["CONTENT_TYPE"] = "text/html";
	map["GATEWAY_INTERFACE"] = "CGI/1.1";
	map["PATH_INFO"] = "/directory/youpi.php";					// 기본 cgi 필수요소
	map["PATH_TRANSLATED"] = "/Users/holee/Desktop/test/Webserv/YoupiBanane/youpi.php";	// 기본 cgi 필수요소
	map["QUERY_STRING"] = "";
	map["REMOTE_ADDR"] = "127.0.0.1";
	map["REMOTE_IDENT"] = "";
	map["REMOTE_USER"] = "";
	map["REQUEST_METHOD"] = "POST";					// 기본 cgi 필수요소
	map["REQUEST_URI"] = "/directory/youpi.php";
	map["SCRIPT_NAME"] = "/Users/holee/Desktop/test/Webserv/YoupiBanane/youpi.php";
	map["SERVER_NAME"] = "first_server";
	map["SERVER_PORT"] = "8080";
	map["SERVER_PROTOCOL"] = "HTTP/1.1";		// 기본 cgi 필수요소
	map["SERVER_SOFTWARE"] = this->m_server_name;

	/* cgi */
	map["HTTP_X_SECRET_HEADER_FOR_TEST"] = '1';				// 기본 cgi 필수요소

	/* php */
	map["REDIRECT_STATUS"] = "200";
	map["SCRIPT_FILENAME"] = "/Users/holee/Desktop/test/Webserv/YoupiBanane/youpi.php";

```

**Comment by hochan222** [comment]
```php
<?php 
	print "Status: 200 OK\r\n";
	print "Content-Type: text/html; charset=utf-8\r\n\r\n";
	phpinfo(INFO_VARIABLES); 
?>
````
youpi.php
