### ISSUE TITLE
[Response] CGI 구현

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#39]
CGI 부분 구현

<img src="https://user-images.githubusercontent.com/22424891/109384473-549e8c80-7930-11eb-8b7b-efb05b98c59b.png" height="500px" />

- [x] envp 만드는 함수
- [ ] pipe 포함 전체 로직

### wiki
- https://github.com/ftinx/webserv/wiki/cgi%EB%9E%80%3F
- https://github.com/get-Pork-Belly/Webserv/wiki/CGI%EC%99%80-%ED%8C%8C%EC%9D%B4%ED%94%84-%EA%B7%B8%EB%A6%AC%EA%B3%A0-dup

```# fcntl```
- https://www.joinc.co.kr/w/Site/system_programing/File/Fcntl

**Comment by hochan222** [comment]
### subject

> Because you are using non-blocking FD, you could use read/recv or
write/send functions without select and your server would be not
blocking. Again trying to read/recv or write/send in any FD without going
through a select will give you a mark equal to 0 and the end of the
evaluation.

> You can only use fcntl as follow: fcntl(fd, F_SETFL, O_NONBLOCK);
Any other flags is forbidden

**Comment by yechoi42** [comment]
```
execve(cgi_path, argv, envp)
```

### envp
envp is an array of pointers to strings, conventionally of the form **key=value**, which are passed as the environment of the new program.  The envp array must be terminated by a NULL pointer.

**Comment by hochan222** [comment]
> envp

- ex

`int main( int argc, char *argv[], char *envp[] )`

**Comment by yechoi42** [comment]
```
execve(cgi_path, argv, envp)
```

### envp
envp is an array of pointers to strings, conventionally of the form **key=value**, which are passed as the environment of the new program.  The envp array must be terminated by a NULL pointer.



### argv

아래와 같은 syntax로 인자를 받기도 한다는 군요. 

`http://www.deadfire.com/cgi-bin/sample2?aaaa+bbbb+$+한글`

argv[0] is [sample2]
argv[1] is [aaaa]
argv[2] is [bbbb]
argv[3] is [\$]
argv[4] is [한글]

http://www.deadfire.net/cgic/cgic08.html

**Comment by yechoi42** [comment]
dup과 dup2의 차이
https://sosal.kr/186

fcntl 활용
https://reakwon.tistory.com/110

block 과 nonblock의 차이
https://ozt88.tistory.com/20

**Comment by yechoi42** [comment]
cgi envp `PATH_INFO`
url 상에서 cgi를 정하고 나머지 부분을 PATH_INFO로 보냄 
`http://localhost/cgi-bin/script.pl/with/additional/path` 에서
`with/additional/path` 

https://github.com/get-Pork-Belly/Webserv/pull/195

**Comment by hochan222** [comment]
이는 일반적으로 문서 모음 내의 새 디렉토리를 CGI 스크립트를 포함하는 것으로 표시하여 수행됩니다 cgi-bin. 그 이름은 종종 . 예를 들어 /usr/local/apache/htdocs/cgi-bin는 웹 서버에서 CGI 디렉토리로 지정 될 수 있습니다. 웹 브라우저가 CGI 디렉토리 (예 :)에있는 파일을 가리키는 URL을 요청하면 http://example.com/cgi-bin/printenv.pl/with/additional/path?and=a&query=string해당 파일 ( /usr/local/apache/htdocs/cgi-bin/printenv.pl)을 웹 브라우저로 보내는 대신 HTTP 서버가 지정된 스크립트를 실행하고 스크립트의 출력을 전달합니다. 웹 브라우저에. 즉, 스크립트가 표준 출력으로 보내는 모든 것은 터미널 창에 화면에 표시되는 대신 웹 클라이언트로 전달됩니다.

- https://en.wikipedia.org/wiki/Common_Gateway_Interface

**Comment by hochan222** [comment]
https://woozle.org/papers/php-cgi.html

**Comment by hochan222** [comment]
다른 레포에있는 YoupiBanane, youpi.bad_extension 이거!!! subject나 다른걸 찾아봐도 안나오는 이거!!! 찾았습니댜...ㅠ tester 돌려보세요ㅠㅠㅠ

아... 그토록 찾던 무엇을 구현해야하는지가 적혀있습니댜.. 와ㅠㅠㅠㅠㅠㅠㅠ 드디어 찾았다ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ subject에 없는 ㅠㅠㅠ

**Comment by yechoi42** [comment]
슬랙 모음 
> webserv CGI에서 php-cgi를 실행할 때는 REDIRECT_STATUS, SCRIPT_FILENAME을 명시해야 만 제대로 실행이 되네요.  삽질좀 했습니다. CGI 표준에 있는 것도 아닌데 이게 뭐람..
> 관련 글 : https://woozle.org/papers/php-cgi.html (편집됨)

**Comment by hochan222** [comment]
cgi를 뽀개보자.

- 2개 파이프
  - https://m.blog.naver.com/sdug12051205/221064264174
 
- 컨트롤 디 안눌러도 진행되게 하는법?

**Comment by hochan222** [comment]
1. fd로 했을 때

<img src="https://user-images.githubusercontent.com/22424891/112940918-c6086f80-9168-11eb-87c8-4b0b0bde9a3e.png" height="300px"/>
<img src="https://user-images.githubusercontent.com/22424891/112940932-cbfe5080-9168-11eb-8179-15e361b77b74.png" height="300px"/>

2. fd int에 넣어서 했을때 

<img src="https://user-images.githubusercontent.com/22424891/112941237-357e5f00-9169-11eb-9f7a-0cb13fcaa186.png" height="300px"/>
<img src="https://user-images.githubusercontent.com/22424891/112941245-3911e600-9169-11eb-81e1-1e0d6f50e9d1.png" height="300px"/>

**Comment by hochan222** [comment]
-- pipe 다음에 넣어줘야함.

**Comment by hochan222** [comment]
- [ ] execve path 맴버변수로 올바른 값 넣기
- [ ] execve의 2번째 파라미터 new_argv에 cgi이름 맴버변수로 넣기
- [ ] 구조

**Comment by hochan222** [comment]
- (c/c++) trying to force EOF from parent process sending input to child process
https://stackoverflow.com/questions/3910253/c-c-trying-to-force-eof-from-parent-process-sending-input-to-child-process

![image](https://user-images.githubusercontent.com/22424891/113129106-7ce21980-9255-11eb-9ebd-dec0d02f75bc.png)

카일 심 슨!!!!?!

**Comment by yechoi42** [comment]
흐아아아앙ㅇ 
```
		write(parent_write, str, 8);
		close(parent_write);
		int status;
		waitpid(pid, &status, 0);
```
부모에서 쓰고 닫고 자식이 끝날때까지 기다려줘야 합니다!!!!!!!!!!!!!!!1

**Comment by hochan222** [comment]
우와오아ㅏ아아ㅘ아아아아ㅗ아앙 ㅠㅠㅠㅠㅠㅠㅠㅠ
드디어 됐땅ㅠㅠㅠㅠㅠㅠㅠ 하핳 죠아요!
