### ISSUE TITLE
Config hpp 요소 정하기

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#4]
Config hpp 요소 정하기

## 설계

- [x] HttpConfig Class Diagram 그리기
- [x] draw.io FILE DIR에 file path 추가하기
- [x] HttpConfig.hpp

## 정해야 하는 조건

- [x] http {} 로 반드시 감싸져있어야한다.  
- [x] listen의 default 값은 42424이고 이후 추가될때마다 1씩 증가 혹은 미기재 혹은 중복시 에러처리한다.
- [x] 비정상 옵션입력시 에러처리 한다.

## File 위치

[<img src="https://user-images.githubusercontent.com/22424891/108587290-2ea84380-7396-11eb-983f-463d3b4f6d96.png" height="300px" />](https://app.diagrams.net/#Hftinx%2Fwebserv%2Fmaster%2Fwebserv_class_diagram.drawio)

## Flow chart

[<img src="https://user-images.githubusercontent.com/22424891/108587395-a1b1ba00-7396-11eb-9847-106965e6c54f.png" height="500px" />](https://app.diagrams.net/#Hftinx%2Fwebserv%2Fmaster%2Fwebserv_class_diagram.drawio)

## Class Diagram

[<img src="https://user-images.githubusercontent.com/22424891/108590343-58696680-73a6-11eb-9d8e-f0b3f358df7e.png" height="700px" />](https://app.diagrams.net/#Hftinx%2Fwebserv%2Fmaster%2Fwebserv_class_diagram.drawio)

#### ```# nginx```
 - https://architectophile.tistory.com/12

**Comment by hochan222** [comment]
## Subject
- [x] We will consider that nginx is HTTP 1.1 compliant and may be use to compare headers and answer behaviors
- [x] Your program should have a config file in argument or use a default path

• In this config file we should be able to
- > You should inspire yourself from the "server" part of nginx configuration file
- [x] choose the port and host of each "server"
- [x] setup the server_names or not
- [x] The first server for a host:port will be the default for this host:port (meaning it will answer to all request that doesn’t belong to an other server)
- [x] setup default error pages
- [x] limit client body size
- [ ] setup routes with one or multiple of the following rules/configuration (routes wont be using regexp):
  - [x] define a list of accepted HTTP Methods for the route
  - [x] define a directory or a file from where the file should be search (for example if url /kapouet is rooted to /tmp/www, url /kapouet/pouic/toto/pouet is /tmp/www/pouic/toto/pouet) 
  - [x] turn on or off directory listing
  - [x] default file to answer if the request is a directory
  - [ ] execute CGI based on certain file extension (for example .php)
    - [x] You wonder what a CGI is go? https://ko.wikipedia.org/wiki/%EA%B3%B5%EC%9A%A9_%EA%B2%8C%EC%9D%B4%ED%8A%B8%EC%9B%A8%EC%9D%B4_%EC%9D%B8%ED%84%B0%ED%8E%98%EC%9D%B4%EC%8A%A4
    - [ ] Because you wont call the cgi directly use the full path as PATH_INFO
    - [ ] Just remember that for chunked request, your server need to unchunked it and the CGI will expect EOF as end of the body.
    - [ ] Same things for the output of the CGI. if no content_length is returned from the CGI, EOF will mean the end of the returned data.
    - [ ] Your program should set the following Meta-Variables
      - [ ] AUTH_TYPE
      - [ ] CONTENT_LENGTH
      - [ ] CONTENT_TYPE
      - [ ] GATEWAY_INTERFACE
      - [ ] PATH_INFO
      - [ ] PATH_TRANSLATED
      - [ ] QUERY_STRING
      - [ ] REMOTE_ADDR
      - [ ] REMOTE_IDENT
      - [ ] REMOTE_USER
      - [ ] REQUEST_METHOD
      - [ ] REQUEST_URI
      - [ ] SCRIPT_NAME
      - [ ] SERVER_NAME
      - [ ] SERVER_PORT
      - [ ] SERVER_PROTOCOL
      - [ ] SERVER_SOFTWARE
    - [ ] Your program should call the cgi with the file requested as first argument
    - [ ] the cgi should be run in the correct directory for relativ path file access
    - [ ]  your server should work with php-cgi
  - [x] make the route able to accept uploaded files and configure where it should be saved
- [x] You should provide some configuration files for evaluation

**Comment by hochan222** [comment]
#### Config File Example
```
http { 
    software_name ftinx;
    software_version 0.1;
    include mime.types;
    root /Users/holee/Documents/Webserv/;
    server {
        server_name first_server;
        listen 8080;
        default_error_page ./www/errors/default_error.html;
        content_length 2048;

        location / {
            limit_except GET;
            cgi .bin .cgi .bla;
            cgi_path /Users/holee/Documents/Webserv/cgi_tester;
			index index.html;
            root /Users/holee/Documents/Webserv/;
        }
        location /put_test {
            limit_except PUT;
            root /Users/holee/Documents/Webserv/tests/put_test;
            cgi .bla;
            cgi_path /Users/holee/Documents/Webserv/cgi_tester;
        }
        location /post_body {
            limit_client_body_size 100;
            limit_except POST;
            index index.html;
            root /Users/holee/Documents/Webserv/tests/folder;
        }
        location /directory { 
            limit_except GET POST;
            index youpi.bad_extension;
            cgi .bla .php;
            cgi_path /Users/holee/Documents/Webserv/YoupiBanane/youpi.bad_extension;
            root /Users/holee/Documents/Webserv/YoupiBanane;
        }
    }
    server {
        server_name second_server;
        listen       8081;
        location /first {
            index  index.html index.htm;
        }
        location /second {
            root /Users/holee/Documents/dev/team_webserv/tests/;
            index  html;
            limit_except PUT POST GET;
            index index.html index.htm index.abc;
        }
    }
}
```

**Comment by hochan222** [comment]
#### CGI
- https://qaos.com/sections.php?op=viewarticle&artid=194
- https://velog.io/@seanlion/cgi

**Comment by jwon42** [comment]
Config file example 수정
```
http {
    software_name ftinx #프로그램명
    software_version 0.1 #버전


    include mime.types
    root /Users/ftinx/Webserv/
#서버블록 시작
    server {
        server_name first_server
        listen 8080
        default_error_page ./www/errors/default_error.html
        content_length 2048
        location / {
            limit_except GET
            cgi .bin .cgi .bla
            cgi_path /Users/holee/Documents/Webserv/cgi_tester
            index index.html
            root /Users/holee/Documents/Webserv/
            autoindex on
        }
        location /put_test {
            limit_except PUT
            root /Users/holee/Documents/Webserv/tests/put_test
            cgi .bla
            cgi_path /Users/holee/Documents/Webserv/cgi_tester
        }
        location /post_body {
            limit_client_body_size 100
            limit_except POST
            index index.html
            root /Users/holee/Documents/Webserv/tests/folder
        }
        location /directory {
            limit_except GET POST
            index youpi.bad_extension
            cgi .bla .php
            cgi_path /Users/holee/Documents/Webserv/YoupiBanane/youpi.bad_extension
            root /Users/holee/Documents/Webserv/YoupiBanane
        }
    }
#첫번째 서버블록 끝, 두번째 서버블록 시작
    server {
        server_name second_server
        listen       8081
        location /first {
            index  index.html index.htm
        }

        location /second {
            root /Users/holee/Documents/dev/team_webserv/tests/
            index  html
            limit_except PUT POST GET
            index index.html index.htm index.abc
        }
    }
#서버블록 끝
}
```
