### ISSUE TITLE
[Utils] std::string  fileToString(std::string path); 구현

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#55]
default 파일로 html, jpg등도 읽을 수 있어야하므로 파라미터로 입력된 path에 있는 파일 전체 내용을 읽어서 string으로 반환하는 함수가 필요해서 이슈 달았습니다.  

```
std::string  fileToString(std::string path);
```

**Comment by jwon42** [comment]
Utils에 포함 예정입니다.

```c++
# include <fcntl.h> // for open function
# include <unistd.h> // for read function
# define BUFFER_SIZE 4096 // for read buffer

std::string fileToString(std::string file_path)
{
	int fd;
	int bytes;
	char buffer[BUFFER_SIZE];
	std::string ret;

	if ((fd = open(file_path.c_str(), O_RDONLY)) < 0)
		throw std::exception();
	ft::memset(buffer, 0, BUFFER_SIZE);
	while ((bytes = read(fd, buffer, BUFFER_SIZE) > 0))
		ret += std::string(buffer);
	if (bytes < 0)
		throw std::exception();
	return (ret);
}
```

**Comment by jwon42** [comment]
> Utils에 포함 예정입니다.
> 
> ```c++
> # include <fcntl.h> // for open function
> # include <unistd.h> // for read function
> # define BUFFER_SIZE 4096 // for read buffer
> 
> std::string fileToString(std::string file_path)
> {
> 	int fd;
> 	int bytes;
> 	char buffer[BUFFER_SIZE];
> 	std::string ret;
> 
> 	if ((fd == open(file_path.c_str(), O_RDONLY)) < 0)
> 		throw std::exception();
> 	ft::memset(buffer, 0, BUFFER_SIZE);
> 	while ((bytes = read(fd, buffer, BUFFER_SIZE) > 0))
> 		ret += std::string(buffer);
> 	if (bytes < 0)
> 		throw std::exception();
> 	return (ret);
> }
> ```

첫번째 if구문 문법 오류 수정했어요

**Comment by jwon42** [comment]
어라.. 문법 오류있나봐요. 수정해볼게요. -> 수정완료!
