### ISSUE TITLE
inet_addr, inet_ntoa, htonl, htons 구현

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#6]
허용되지 않은 함수들(inet_addr, inet_ntoa, htonl, htons) 구현

#### 진행 사항
- [x] inet_addr
- [x] inet_ntoa
- [x] htonl
- [x] htons

---

#### 정해야 되는 사항
- 구현할 디렉토리와 파일이름
- class나 namespace로 구현 할지말지

- - -

#### 결정 사항

**Comment by jwon42** [comment]
- htons, htonl, ntohl, ntohs
  https://blishk.tistory.com/9
  https://www.gta.ufrj.br/ensino/eel878/sockets/htonsman.html
  https://www.freebsd.org/cgi/man.cgi?query=htonl
- htonl function (winsock.h)
  https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-htonl
- htons function (winsock.h)
  https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-htons
- ntohl function (winsock.h)
  https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-ntohl
- ntohs function (winsock.h)
  https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-ntohs

**Comment by jwon42** [comment]
inet_addr은 허용함수에 있음.

**Comment by jwon42** [comment]
inet_ntoa
http://ehpub.co.kr/tag/inet_ntoa-%ED%95%A8%EC%88%98/
https://karfn84.tistory.com/entry/CNetwork-inetntoaint-in-%ED%95%A8%EC%88%98%EC%9D%98-%EA%B5%AC%ED%98%84
https://codingdog.tistory.com/entry/mysql-inetntoa-inetaton-%ED%95%A8%EC%88%98-ipv4-%EC%A3%BC%EC%86%8C%EB%A5%BC-%EC%96%B4%EB%96%BB%EA%B2%8C-%EB%8B%A4%EB%A3%B0%EA%B9%8C%EC%9A%94
