### ISSUE TITLE
[Server] Nginx autoindex 구현

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#60]
- Front
  - http 요청으로 현재 디렉토리 목록 반환
  - href 기능 제공
- Back
  - autoindex 로직 분기
  - 기본 경로는 www 폴더
  - 요청된 경로에 대한 ls 목록 response

**Comment by jwon42** [comment]
- http://www.nsc.ru/cgi-bin/www/unix_help/unix-man?stat+2
- https://modoocode.com/109
- https://raw.githubusercontent.com/fulicat/autoindex/master/autoindex_after.png
- https://stackoverflow.com/questions/11880892/html-table-highlight-row-on-hover-except-first-row-header
