### ISSUE TITLE
CGI 구현

### ISSUE THREAD

**Issue by hochan222** [ftinx/webserv#7]
cgi 파일 구현 및 무엇인지 알기

## 구현 사항

- [ ] CGI 예시를  /www/cgi-bin 폴더에 구현

## 폴더
[<img src="https://user-images.githubusercontent.com/22424891/108584083-c3ed0d00-7381-11eb-8043-bfcd1d9699ec.png" height="200px" />](https://docs.google.com/presentation/d/1tRcPkT9RgT2v9z4UzZacN5C6YAEGqjkIVvCDYdL9_8E/edit#slide=id.g79a85b2d57_0_150)

- /www/cgi-bin 폴더에 구현

## spec

- [issue (#4)](https://github.com/ftinx/webserv/issues/4)   2번째 댓글 참고

## 참고
> 관례적으로 / var / www / cgi-bin으로 이름이 지정됩니다. 
> 관례상 CGI 파일 은 C ++ 실행 가능하지만 확장자는 .cgi 입니다.

```c++
#include <iostream>
using namespace std;

int main () {
   cout << "Content-type:text/html\r\n\r\n";
   cout << "<html>\n";
   cout << "<head>\n";
   cout << "<title>Hello World - First CGI Program</title>\n";
   cout << "</head>\n";
   cout << "<body>\n";
   cout << "<h2>Hello World! This is my first CGI program</h2>\n";
   cout << "</body>\n";
   cout << "</html>\n";
   
   return 0;
}
```
> C ++ 코드를 컴파일하고 실행 파일의 이름을 cplusplus.cgi로 지정
- https://www.tutorialspoint.com/cplusplus/cpp_web_programming.htm

**Comment by yechoi42** [comment]
## CGI



cgi 는 두개의 서로 다른 프로토콜을 연동하는(소프트웨어 게이트웨이) 표준안이다. CGI 표준을 따라 만들어진 프로그램을 CGI 프로그램 또는 스크립트라고 한다. 

cgi도 웹에서 http를 통해 동작하므로 http와 동일한 절차(접속-요청-응답-접속해제)로 동작. 

차이는 일반적인 경우 웹상의 요청은 하이퍼링크를 통해 이뤄지지만, cgi의 요청은 주로 form 태그나 isindex 태그를 통해 이뤄진다. 또한 파일시스템에서 문서를 읽어 전송하는 게 아니라, cgi 프로그램이 동적으로 생성하는 문서를 클라이언트에 전송한다.


사용자가 form 태그의 제출(submit) 버튼을 클릭하면 클라이언트는 현재 시간, 날짜와 같은 시스템 정보와 사용자 ID, 도메인명과 같은 사용자 정보를 포함한 요청 메세지(request message)를 웹 서버에 전송한다.

웹서버는 요청된 url 이 어떤 종류의 파일(ssi, gci, perl)인지 분석하고, cgi 프로그램일 경우 요청 헤더에 포함된 상태정보를 환경변수(QUERY_STRING, CONTENT_LENGHT 등등)로 설정하고 나서 cgi 프로그램을 실행시키게 된다.

그러면 cgi 프로그램은 다른 서비스를 이용하기 위해 다른 프로그램을 또다시 호출하거나, 직접 처리를 한 다음 사용자에게 보여줄 문서를 표준 출력으로 보내게 된다. 이것을 받은 서버는 다시 클라이언트 쪽으로 네트워크를 통해 결과를 전송하게 된다. 

Cgi 스크립트는 표준에 따라 `Content-Type:Main-Type/Sub-Type\n\n` 을 먼저 출력하고 헤더와 바디를 구분하기 위해 공백 라인을 하나 추가해야 한다. 이 형식에 맞지 않으면 서버는 '500 Internal Server Error'를 출력한다. 

Content-Type은 일반 텍스트 파일인 경우는 `text/html`, html 문서일 경우는 `text/html` , jpeg 이미지일 경우는 `images/jpeg` 등이 가능하며 각각의 파일에 따라서 MIME 유형이 정의돼 있다. 

문서는 Content-Type 에 맞게 출력해야 한다. Html 파일의 경우 <html><body> ~</body></html> 태그 추가.


### 500 error

500 Internal Server Error 가 발생하는 이유는 다음의 주의사항을 지키지 않았기 때문

- cgi의 확장자는 `.cgi`로 한다
- 안전하고 효율적인 관리를 위해 cgi-bin/ 디렉토리에서 스크립트 관리
- 퍼미션
  - cgi 프로그램 755
  - 데이터 파일 666
  - 읽기/쓰기용 디렉토리 777
- cgi 출력 형식은 표준을 따른다(위에서 이미 기술)
- web에서 실행


### 입력

웹서버에서 cgi로, cgi 프로그램에서 웹서버로 서로 통신하는 방법이 마련돼있어야 한다. 우선 cgi 입력은 크게 세가지 방법을 통해 이뤄진다. 



#### 환경변수

form 태그에서 method를 get으로 하거나 isindex 태그를 사용하는 경우, cgi 입력은 환경변수로부터 받아들여진다. 



#### 표준입력

입력 폼에서 post 를 사용했을 경우에는 표준입력으로 데이터가 전달된다. 서버가 데이터 끝에 eof 심볼을 삽입하지 않을 수도 있기 때문에, 환경변수 CONTENT_LENGTH를 읽어들여 그 값만큼 데이터를 읽어들여야 한다. 



#### 명령행

isindex를 사용한 경우 명령행의 매개변수로 인자를 넘겨받을 수 있다. 명령행이 사용된 것을 알아내기 위해서는 클라이언트로부터 전달된 데이터에 인코딩이 되지 않은 '='를 찾으면 된다. 


### 출력

cgi 프로그램의 출력은

- 동적으로 생성해낸 새로운 문서(content-type)일 수도 있고
- 서버가 특정한 문서를 되돌려 주도록 하는 지시정보(Locations) 일 때도 있으며
- 단지 명령의 수행 결과를 리턴하는 상태라인(status)일 수도 있다

cgi 프로그램의 출력은 반드시 content-type, location, status-line 중 하나를 가장 먼저 출력해야 한다. 

이러한 헤더에 이어 빈줄이 하나 삽입돼야 하며, 그렇지 않으면 500에러를 발생한다. 



#### Content-Type: 리턴될 문서의 MIME 타입

MIME 타입 중 하나를 Content-type 헤더를 이용해 출력한다.

- `Content-Type:` Content-Type 과 콜론 사이에 공백이 존재해선 안된다



#### Location: 리턴될 문서의 URL

웹 서버는 이 헤더를 만나면, 헤더 값이 절대경로면 문서를 직접 돌려준다.

완전한 URL일 경우에는 클라이언트에 리다이렉트를 보내준다. 리다이렉트를 하는 경우 3xx번대 상태코드를 전송한다. 



#### Status Line

일반적으로는 cgi 프로그램을 수행할 때, 서버는 cgi 프로그램의 출력에 추가 헤더와 상태 정보를 덧붙여 클라이언트에 전송한다. Cgi 프로그램이 상태정보를 직접 출력하는 경우는 서버를 경유하지 않는 경우이므로, 우리의 케이스에는 해당하지 않는 듯? 



---

기타 보안 관련 유의 사항 

- cgi 프로그램이 웹서버에서 실행될 때 자식 프로세스의 권한으로 실행
- 안전하고 효율적인 관리를 위해 cgi-bin/ 디렉토리에서 스크립트 관리
- 스크립트의 소스가 노출되는 것을 방지하기 위해 되도록 컴파일
- cgi-bin/ 디렉토리를 711(drwx--x--x)의 권한을 부여, 정확한 cgi 파일 이름을 알고 있어야만 접근하도록
- cgi 스크립트는  -rwxr-xr-x, 컴파일된 프로그램은 -rwx--x--x의 권한 부여
- PATH에 의존하는 쉘명령어를 실행하지 않는 게 좋음 (ls 보단 /bin/ls)
- 꼭 PATH에 의존하는 쉘명령어를 실행시키고 싶다면 cgi 프로그램 처음에 PATH를 설정해주는 게 좋음

**Comment by yechoi42** [comment]
The following are environment variables passed to CGI programs:

Server specific variables:

- [ ] SERVER_SOFTWARE: name/version of HTTP server.
- [ ] SERVER_NAME: host name of the server, may be dot-decimal IP address.
- [ ] GATEWAY_INTERFACE: CGI/version.

Request specific variables:

- [ ] SERVER_PROTOCOL: HTTP/version.
- [ ] SERVER_PORT: TCP port (decimal).
- [ ] REQUEST_METHOD: name of HTTP method (see above).
- [ ] PATH_INFO: path suffix, if appended to URL after program name and a slash.
- [ ] PATH_TRANSLATED: corresponding full path as supposed by server, if PATH_INFO is present.
- [ ] SCRIPT_NAME: relative path to the program, like /cgi-bin/script.cgi.
- [ ] QUERY_STRING: the part of URL after ? character. The query string may be composed of *name=value pairs separated with ampersands (such as var1=val1&var2=val2...) when used to submit form data transferred via GET method as defined by HTML application/x-www-form-urlencoded.
- [ ] REMOTE_HOST: host name of the client, unset if server did not perform such lookup.
- [ ] REMOTE_ADDR: IP address of the client (dot-decimal).
- [ ] AUTH_TYPE: identification type, if applicable.
- [ ] REMOTE_USER used for certain AUTH_TYPEs.
- [ ] REMOTE_IDENT: see ident, only if server performed such lookup.
- [ ] CONTENT_TYPE: Internet media type of input data if PUT or POST method are used, as provided via HTTP header.
- [ ] CONTENT_LENGTH: similarly, size of input data (decimal, in octets) if provided via HTTP header.
- [ ] Variables passed by user agent (HTTP_ACCEPT, HTTP_ACCEPT_LANGUAGE, HTTP_USER_AGENT, HTTP_COOKIE and possibly others) contain values of corresponding HTTP headers and therefore have the same sense.
