### ISSUE TITLE
fd_set 조작 함수 (fdSet, fdIsset, fdClr, fdZero 등) 구현

### ISSUE THREAD

**Issue by jwon42** [ftinx/webserv#8]
fd_set 조작 함수 (fdSet, fdIsset, fdClr, fdZero 등) 구현

#### 진행 사항
- [x] fdSet
- [x] fdIsset
- [x] fdClr
- [x] fdZero

---

#### 정해야 되는 사항
- 더 필요한 함수가 있는지 여부

- - -

#### 결정 사항
-

**Comment by hochan222** [comment]
- __FD_ZERO__
  - FD_ZERO(fd_set *fdset) 
  - *fdset의 모든 비트를 지운다.
- __FD_SET__
  - FD_SET(int fd, fd_set *fdset)
  - *fdset 중 소켓 fd에 해당하는 비트를 1로 한다.
- __FD_CLR__
  - FD_CLR(int fd, fd_set *fdset)
  - *fdset 중 소켓 fd에 해당하는 비트를 0으로 한다.
- __FD_ISSET__
  - FD_ISSET(int fd, fd_set *ftset)
  - *fdset 중 소켓 fd에 해당하는 비트가 세트되어 있으면 양수값인 fd를 리턴한다.

### ft_set

```c++
typedef struct fd_set {
    u_int        fd_count;   // 소켓핸들의 수
    SOCKET   fd_array(FD_SETSIZE); // 소켓 핸들의 배열
} fd_set;

**Comment by jwon42** [comment]
fd, fd_set, fd_zero, FD_SET, FD_CLR, FD_ISSET 이란?
http://blog.naver.com/tipsware/220810795410
https://www.crocus.co.kr/542
